AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Rak Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs10.x
      CodeUri: .
      Description: 'Lambda function for Rak Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::052160034011:role/CFRole'
      Events:
        time:
          Type: Api
          Properties:
            Path: /time
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
